#!/usr/bin/env php
<?php
/**
 * 定义项目根目录
 */
define('BASE_PATH',str_replace('\\','/',realpath(dirname(__FILE__).'/'))."/");
require_once "core/Application.php";
 \core\Application::run()->console($argv);